sections:
  main:
    display: Main
    fields:
      -
        handle: website_name
        field:
          input_type: text
          antlers: false
          display: 'Website Name'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: website_description
        field:
          antlers: false
          display: 'Website Description'
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: website_logo
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          display: 'Website Logo'
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: website_favicon
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          display: 'Website Favicon'
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: website_email
        field:
          input_type: text
          antlers: false
          display: 'Website Email'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: website_phone
        field:
          input_type: text
          antlers: false
          display: 'Website Phone'
          type: text
          icon: text
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: website_address
        field:
          antlers: false
          display: 'Website Address'
          type: textarea
          icon: textarea
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
      -
        handle: website_quotation
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          display: 'Website Quotation'
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          always_save: false
